ems_web/adminapp/urls.py
from django.urls import path, include
import adminapp.views as views

app_name = 'adminapp'
urlpatterns = [
    path('regist/',views.regist, name = 'regist'),
    path('registdo/',views.registdo, name = 'registdo'),
    path('getcaptcha/',views.getcaptcha, name = 'getcaptcha'),
    path('login/',views.login, name = 'login'),
    path('logindo/',views.logindo, name = 'logindo'),
]

ems_web/doapp/urls.py
from django.urls import path
import doapp.views as views
app_name = 'doapp'
urlpatterns = [
    path('emplist/',views.emplist, name = 'emplist'),
    path('addemp/',views.addemp, name = 'addemp'),
    path('addempdo/',views.addempdo, name = 'addempdo'),
    path('deleteemp/',views.deleteemp, name = 'deleteemp'),
    path('updateemp/',views.updateemp, name = 'updateemp'),
    path('updateempdo/',views.updateempdo, name = 'updateempdo'),
]

ems_web/ems_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/',include('adminapp.urls')),
    path('doapp/',include('doapp.urls')),
]

ems_web/adminapp/models.py
from django.db import models

# Create your models here.

class Admin(models.Model):
    username = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    sex = models.BooleanField(default=True)

class aaa(models.Model):
    username = models.CharField(max_length=20)
    name = models.CharField(max_length=20)

class Emp(models.Model):
    name = models.CharField(max_length=20)
    salary = models.SmallIntegerField()
    age = models.SmallIntegerField()
    head = models.FileField(upload_to='imgs')

ems_web/doapp/models.py
from django.db import models

# Create your models here.

ems_web/adminapp/views.py
import random
import string

from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from adminapp.captcha.image import ImageCaptcha
from adminapp.models import Admin


def regist(request):
    return render(request,"adminapp/regist.html")

def registdo(request):
    username = request.POST.get('username')
    name = request.POST.get('name')
    password = request.POST.get('pwd')
    sex = request.POST.get('sex')
    if sex == 'true':
        sex = True
    else:
        sex = False
    number = request.POST.get('number')
    print(username,name,password,sex,number)
    code = request.session['code']
    if number.lower() == code.lower():
        Admin.objects.create(username=username,name=name,password=password,sex=sex)
        return redirect("adminapp:login")
    else:
        return redirect("adminapp:regist")

def getcaptcha(request):
    img = ImageCaptcha()
    rst = random.sample(string.ascii_letters+string.digits,5)
    print(rst)
    code = ''.join(rst)
    print(code)
    request.session['code'] = code
    data = img.generate(code)
    return HttpResponse(data,'image/png')

def login(request):
    if request.COOKIES.get('password') and  request.COOKIES.get('username'):
        request.session['login'] = 'login'
        print('jjjjjjjjjjjjjjjjjjjjjjjjjjj')
        return redirect('doapp:emplist')
    else:
        return render(request,"adminapp/login.html")
    # if request.COOKIES['password'] == Admin.objects.get(username=request.COOKIES['username']).password:
    #     return redirect('doapp:emplist')
    # return render(request,"adminapp/login.html")

def logindo(request):
    name = request.POST.get('name')
    password = request.POST.get('pwd')
    if Admin.objects.get(username=name).password == password:
        request.session['login'] = 'login'
        red = redirect('doapp:emplist')
        red.set_cookie("username",name)
        red.set_cookie("password",password)
        return red
    else:
        return redirect('adminapp:login')

ems_web/doapp/views.py
import os
import uuid

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
from adminapp.models import Emp


def emplist(request):
    if request.session.get('login'):
        number = request.GET.get('page')
        print(number)
        if number is None:
            number = 1
        emp = Emp.objects.all()
        pagntor = Paginator(emp, per_page=3)
        pg = pagntor.page(number)
        return render(request, 'doapp/emplist.html', {'page': pg})
    else:
        return redirect('adminapp:login')

def addemp(request):
    if request.session.get('login'):
        # return redirect('doapp:emplist')
        print('lllll')
        return render(request, 'doapp/addEmp.html')
    else:
        return redirect('adminapp:login')

def addempdo(request):
    name = request.POST.get('name')
    salary = request.POST.get('salary')
    age = request.POST.get('age')
    head = request.FILES.get('head')

    rst = str(uuid.uuid4()) + os.path.splitext(head.name)[1]
    head.name = rst
    print(name, salary, age, head)
    Emp.objects.create(name = name, salary = salary, age = age, head = head)
    return redirect('doapp:emplist')

def deleteemp(request):
    id = request.GET.get('id')
    # print(id)
    # name = request.GET.get('name')
    Emp.objects.get(id = id).delete()
    return redirect('doapp:emplist')

def updateemp(request):
    id = request.GET.get('id')
    return render(request,'doapp/updateEmp.html',{'id':id})

def updateempdo(request):
    id = request.GET.get('id')
    name = request.POST.get('name')
    salary = request.POST.get('salary')
    age = request.POST.get('age')
    head = request.FILES.get('head')

    rst = str(uuid.uuid4()) + os.path.splitext(head.name)[1]
    head.name = rst
    print(name, salary, age, head)
    emp = Emp.objects.get(id = id)
    emp.name = name
    emp.age = age
    emp.salary = salary
    emp.head = head
    emp.save()
    return redirect('doapp:emplist')

ems_web/templates/adminapp/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
{% load static %}
	<head>
		<title>login</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	</head>

	<body>

		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="timenow">
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						login
					</h1>
					<form action="{% url 'adminapp:logindo' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									username:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									password:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Submit &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
        <script>
            var date=new Date();
            var year=date.getFullYear();
            var month=date.getMonth()+1;
            var day=date.getDate();
            var hh=date.getHours();
            var mm=date.getMinutes();
            var ss=date.getSeconds();
            var rq=year+"年"+month+"月"+day+"日"+hh+":"+mm+":"+ss;
            document.getElementById("timenow").innerHTML=rq
        </script>
	</body>
</html>

ems_web/templates/adminapp/regist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/static/style.css" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="timenow">
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						注册
					</h1>
					<form action="{% url 'adminapp:registdo' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="username" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									真实姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									性别:
								</td>
								<td valign="middle" align="left">
									男
									<input type="radio" class="inputgri" name="sex" value=true checked="checked"/>
									女
									<input type="radio" class="inputgri" name="sex" value=false />
								</td>
							</tr>
							
							<tr>
								<td valign="middle" align="right">
									验证码:
									<img id="num" src="{% url 'adminapp:getcaptcha' %}" style="width: 100px"/>
									<a href="javascript:;" onclick="document.getElementById('num').src = '{% url 'adminapp:getcaptcha' %}?'+ new Date().getTime()">换一张</a>
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="number" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Submit &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
        <script>
            var date=new Date();
            var year=date.getFullYear();
            var month=date.getMonth()+1;
            var day=date.getDate();
            var hh=date.getHours();
            var mm=date.getMinutes();
            var ss=date.getSeconds();
            var rq=year+"年"+month+"月"+day+"日"+hh+":"+mm+":"+ss;
            document.getElementById("timenow").innerHTML=rq
        </script>
	</body>
</html>

ems_web/templates/doapp/addEmp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>add Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="/static/style.css" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="timenow">
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						add Emp info:
					</h1>
					<form action="{% url 'doapp:addempdo' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									name:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									salary:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									age:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" />
								</td>
							</tr>
                            <tr>
								<td valign="middle" align="right">
									head:
								</td>
								<td valign="middle" align="left">
									<input type="file" class="inputgri" name="head" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
        <script>
            var date=new Date();
            var year=date.getFullYear();
            var month=date.getMonth()+1;
            var day=date.getDate();
            var hh=date.getHours();
            var mm=date.getMinutes();
            var ss=date.getSeconds();
            var rq=year+"年"+month+"月"+day+"日"+hh+":"+mm+":"+ss;
            document.getElementById("timenow").innerHTML=rq
        </script>
	</body>
</html>

ems_web/templates/doapp/emplist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>emplist</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/static/style.css" />
	</head>
	<body>
        {% load static %}
		<div id="wrap">
			<div id="top_content"> 
				<div id="header">
					<div id="rightheader">
						<p id="timenow">

							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						Welcome!
					</h1>
					<table class="table">
						<tr class="table_header">
							<td>
								ID
							</td>
							<td>
								Name
							</td>
							<td>
								Salary
							</td>
							<td>
								Age
							</td>
                            <td>
                                Head
                            </td>
							<td>
								Operation
							</td>
						</tr>
                        {% for foo in page %}
                            <tr>
                                <td>{{ foo.id }}</td>
                                <td>{{ foo.name }}</td>
                                <td>{{ foo.salary }}</td>
                                <td>{{ foo.age }}</td>
{#                静态资源调用方法，django笔记6有#}
                                <td><img src="{% static foo.head.url%}" alt="" style="width: 100px"></td>
                                <td><a href="{% url 'doapp:deleteemp' %}?id={{ foo.id }}">delete emp</a>&nbsp;<a href="{% url 'doapp:updateemp' %}?id={{ foo.id }}">update emp</a></td>
                            </tr>
                        {% endfor %}
					</table>
                    {% if page.has_previous %}
                        <a href="{% url 'doapp:emplist' %}?page={{ page.previous_page_number }}">上一页</a>
                    {% endif %}

                    {% for foo in page.paginator.page_range %}
                        <a href="{% url 'doapp:emplist' %}?page={{ foo }}">
                            {% if page.number == foo %}
{#                                本页序号变色#}
                                <span style="color: red">{{ foo }}</span>
                                {% else %}
                                <span>{{ foo }}</span>
                            {% endif %}
                        </a>
                    {% endfor %}
                    {% if page.has_next %}
                        <a href="{% url 'doapp:emplist' %}?page={{ page.next_page_number }}">下一页</a>
                    {% endif %}
					<p>
						<input type="button" class="button" value="Add Employee" onclick="location='../addemp/'"/>
					</p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
        <script>
            var date=new Date();
            var year=date.getFullYear();
            var month=date.getMonth()+1;
            var day=date.getDate();
            var hh=date.getHours();
            var mm=date.getMinutes();
            var ss=date.getSeconds();
            var rq=year+"年"+month+"月"+day+"日"+hh+":"+mm+":"+ss;
            document.getElementById("timenow").innerHTML=rq
        </script>
	</body>
</html>

ems_web/templates/doapp/updateEmp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>update Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="/static/style.css" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						update Emp info:
					</h1>
					<form action="{% url 'doapp:updateempdo' %}?id={{ id }}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									id:
								</td>
								<td valign="middle" align="left">
									{{ id }}
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									name:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" value="zhangshan"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									salary:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" value="20000"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									age:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" value="20"/>
								</td>
							</tr>
                             <tr>
								<td valign="middle" align="right">
									head:
								</td>
								<td valign="middle" align="left">
									<input type="file" class="inputgri" name="head" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
            <script>
            var date=new Date();
            var year=date.getFullYear();
            var month=date.getMonth()+1;
            var day=date.getDate();
            var hh=date.getHours();
            var mm=date.getMinutes();
            var ss=date.getSeconds();
            var rq=year+"年"+month+"月"+day+"日"+hh+":"+mm+":"+ss;
            document.getElementById("timenow").innerHTML=rq
        </script>
	</body>
</html>